package com.monoblocks;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.ShapedOreRecipe;

public class MRecipes {
   public MRecipes()
   {
      GameRegistry.addRecipe(new ItemStack(MBlocks.Showcase, 1), new Object[]{"XXX", "XYX", "XXX", 'X', new ItemStack(Blocks.glass, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlackStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.RedStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlueStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 4)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GreenStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 2)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PinkStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 9)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.YellowStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 11)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GrayStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 8)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LgrayStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 7)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.Lbluestone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 12)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.MagentaStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 13)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PurpleStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 5)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.WhiteStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 15)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.OrangeStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 14)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BrownStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 3)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LimeStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 10)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.CyanStone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.dye, 1, 6)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlackPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BluePlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 4)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BrownPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 3)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.CyanPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 6)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GrayPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 8)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GreenPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 2)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.Lblueplanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 12)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.Lgrayplanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 7)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LimePlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 10)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.MagentaPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 13)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.OrangePlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 14)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.RedPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PinkPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 9)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PurplePlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 5)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.WhitePlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 15)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.YellowPlanks.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.planks, 1), '7', new ItemStack(Items.dye, 1, 11)});
      GameRegistry.addRecipe(new ItemStack(MItems.RedSword, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Items.wooden_sword, 1), '7', new ItemStack(Items.dye, 1, 1)});
      GameRegistry.addRecipe(new ItemStack(MItems.BlueSword, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Items.wooden_sword, 1), '7', new ItemStack(Items.dye, 1, 4)});
      GameRegistry.addRecipe(new ItemStack(MItems.BlueLightSaber, 1), new Object[]{"XX3", "X5X", "6XX", '6', new ItemStack(Items.iron_ingot, 1), '5', new ItemStack(Blocks.beacon, 1), '3', new ItemStack(Items.diamond)});
      GameRegistry.addRecipe(new ItemStack(MItems.RedCrystal, 1), new Object[]{"X2X", "252", "X2X", '2', new ItemStack(Items.redstone, 1), '5', new ItemStack(Items.diamond, 1)});
      GameRegistry.addRecipe(new ItemStack(MItems.RedLightSaber, 1), new Object[]{"XX3", "X5X", "6XX", '6', new ItemStack(Items.iron_ingot, 1), '5', new ItemStack(Blocks.beacon, 1), '3', new ItemStack(MItems.RedCrystal)});
      GameRegistry.addRecipe(new ItemStack(MItems.GreenLightsaber, 1), new Object[]{"XX3", "X5X", "6XX", '6', new ItemStack(Items.iron_ingot, 1), '5', new ItemStack(Blocks.beacon, 1), '3', new ItemStack(Items.emerald)});
      GameRegistry.addRecipe(new ItemStack(MItems.PurpleCrystal, 1), new Object[]{"X2X", "252", "X2X", '2', new ItemStack(Items.dye, 1, 5), '5', new ItemStack(Items.nether_star, 1)});
      GameRegistry.addRecipe(new ItemStack(MItems.PurpleLightsaber, 1), new Object[]{"XX3", "X5X", "6XX", '6', new ItemStack(Items.iron_ingot, 1), '5', new ItemStack(Blocks.beacon, 1), '3', new ItemStack(MItems.PurpleCrystal)});
      GameRegistry.addRecipe(new ItemStack(MItems.FleshDye, 1), new Object[]{"12X", "XXX", "XXX", '1', new ItemStack(Items.dye, 1, 15), '2', new ItemStack(Items.dye, 1, 14)});
      GameRegistry.addRecipe(new ItemStack(MItems.RainbowDye, 8), new Object[]{"123", "456", "789", '2', new ItemStack(Items.dye, 1, 15), '1', new ItemStack(Items.dye, 1, 14), '3', new ItemStack(Items.dye, 1, 5), '4', new ItemStack(Items.dye, 1, 7), '5', new ItemStack(Items.dye, 1, 13), '6', new ItemStack(Items.dye, 1, 2), '7', new ItemStack(Items.dye, 1, 4), '8', new ItemStack(Items.dye, 1, 6), '9', new ItemStack(Items.dye, 1, 9)});
      GameRegistry.addRecipe(new ItemStack(MItems.InvisibleDye, 1), new Object[]{"XXX", "12X", "XXX", '2', new ItemStack(Items.dye, 1, 15), '1', new ItemStack(Items.dye, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(MItems.Blaster, 1), new Object[]{"112", "45X", "XXX", '1', new ItemStack(Blocks.wool, 1, 15), '5', new ItemStack(Blocks.wool, 1, 15), '2', new ItemStack(Items.bow, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlackStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.RedStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlueStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 4)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GreenStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 2)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PinkStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 9)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.YellowStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 11)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GrayStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 8)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LGrayStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 7)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LBlueStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 12)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.MagentaStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 13)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PurpleStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 5)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.WhiteStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 15)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.OrangeStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 14)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BrownStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 3)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LimeStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 10)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.CyanStoneBrick.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.stonebrick, 1), '7', new ItemStack(Items.dye, 1, 6)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlackGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.RedGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlueGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 4)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GreenGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 2)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PinkGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 9)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.YellowGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 11)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GrayGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 8)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LgrayGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 7)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LblueGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 12)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.MagentaGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 13)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PurpleGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 5)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.WhiteGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 15)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.OrangeGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 14)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BrownGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 3)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LimeGlowstone.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.glowstone, 1), '7', new ItemStack(Items.dye, 1, 10)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.EternalLoadingBlock, 1), new Object[]{"121", "131", "121", '1', new ItemStack(Items.iron_ingot, 1), '2', new ItemStack(Blocks.glass_pane, 1), '3', new ItemStack(Items.redstone, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Mud, 1), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(MItems.MudBall, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Mud, 1), new Object[]{"12X", "XXX", "XXX", '1', new ItemStack(Blocks.dirt, 1), '2', new ItemStack(Items.water_bucket)});
      GameRegistry.addRecipe(new ItemStack(MItems.IcedCapp, 1), new Object[]{"X1X", "X2X", "X3X", '1', new ItemStack(Items.sugar, 1), '2', new ItemStack(Items.milk_bucket), '3', new ItemStack(Blocks.ice)});
      GameRegistry.addRecipe(new ItemStack(MItems.BigMac, 2), new Object[]{"X1X", "X2X", "X3X", '1', new ItemStack(Items.bread, 1), '2', new ItemStack(MItems.BeefPattie), '3', new ItemStack(Items.bread)});
      GameRegistry.addRecipe(new ItemStack(MItems.BeefPattie, 3), new Object[]{"11X", "XXX", "XXX", '1', new ItemStack(Items.beef, 1)});
      GameRegistry.addRecipe(new ItemStack(MItems.Fries, 3), new Object[]{"111", "XXX", "XXX", '1', new ItemStack(Items.potato, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PurpleCrystalBlock, 1), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(MItems.PurpleCrystal, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.RedCrystalBlock, 1), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(MItems.RedCrystal, 1)});
      GameRegistry.addRecipe(new ItemStack(MItems.SiftingSheet, 1), new Object[]{"X1X", "111", "X1X", '1', new ItemStack(Items.string, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GoldenSand, 1), new Object[]{"21X", "XXX", "XXX", '1', new ItemStack(MItems.SiftingSheet, 1), '2', new ItemStack(MBlocks.Mud)});
      GameRegistry.addRecipe(new ItemStack(Items.gold_nugget, 1), new Object[]{"21X", "XXX", "XXX", '1', new ItemStack(MBlocks.GoldenSand, 1), '2', new ItemStack(MItems.SiftingSheet)});
      GameRegistry.addRecipe(new ItemStack(MItems.MagicBigMac, 1), new Object[]{"21X", "XXX", "XXX", '1', new ItemStack(Blocks.dragon_egg, 1), '2', new ItemStack(MItems.BigMac)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.blockIronFurnaceIdle, 1), new Object[]{"111", "1X1", "111", '1', new ItemStack(Blocks.iron_block, 1)});
      GameRegistry.addRecipe(new ItemStack(MItems.IronSiftingSheet, 7), new Object[]{"X1X", "111", "X1X", '1', new ItemStack(Items.iron_ingot, 1)});
      GameRegistry.addRecipe(new ItemStack(MItems.IronStick, 4), new Object[]{"1XX", "1XX", "XXX", '1', new ItemStack(Items.iron_ingot, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.smoothiron.GetBlock(), 4), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(Blocks.iron_block, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.gold.GetBlock(), 4), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(Blocks.gold_block, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.diamond.GetBlock(), 4), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(Blocks.diamond_block, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Sifter, 1), new Object[]{"121", "1X1", "XXX", '1', new ItemStack(MItems.IronStick, 1), '2', new ItemStack(MItems.IronSiftingSheet, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlackIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.RedIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BlueIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 4)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GreenIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 2)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PinkIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 9)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.YellowIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 11)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.GrayIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 8)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LgrayIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 7)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LblueIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 12)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.MagentaIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 13)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.PurpleIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 5)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.WhiteIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 15)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.OrangeIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 14)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.BrownIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 3)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.LimeIron.GetBlock(), 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(Blocks.iron_block, 1), '7', new ItemStack(Items.dye, 1, 10)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.RoundBBQ, 1), new Object[]{"121", "333", "XXX", '1', new ItemStack(Items.iron_ingot, 1), '2', new ItemStack(Blocks.coal_block), '3', new ItemStack(MItems.IronStick)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.Andesite.GetBlock(), 1), new Object[]{"12X", "21X", "XXX", '1', new ItemStack(Blocks.stone, 1), '2', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.Diorite.GetBlock(), 1), new Object[]{"22X", "11X", "XXX", '1', new ItemStack(Blocks.stone, 1), '2', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.Granite.GetBlock(), 1), new Object[]{"12X", "12X", "XXX", '1', new ItemStack(Blocks.stone, 1), '2', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.SmoothAndesite.GetBlock(), 1), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(MBlocksEnum.Andesite.GetBlock(), 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.SmoothDiorite.GetBlock(), 1), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(MBlocksEnum.Diorite.GetBlock(), 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.SmoothGranite.GetBlock(), 1), new Object[]{"11X", "11X", "XXX", '1', new ItemStack(MBlocksEnum.Granite.GetBlock(), 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.BlackLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.BlackGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.RedLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.RedGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.BlueLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.BlueGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GreenLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.GreenGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PinkLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.PinkGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.YellowLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.YellowGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GrayLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.GrayGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.LgrayLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.LgrayGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.LblueLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.LblueGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.MagentaLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.MagentaGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PurpleLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.PurpleGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.WhiteLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.WhiteGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.OrangeLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.OrangeGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.BrownLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.BrownGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.LimeLamp, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.LimeGlow, 1), '7', new ItemStack(Blocks.redstone_torch)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Flasher, 1), new Object[]{"XXX", "XXX", "67X", '6', new ItemStack(MBlocks.WhiteLamp, 1), '7', new ItemStack(Items.repeater)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.TrafficCone, 4), new Object[]{"X1X", "X1X", "222", '1', new ItemStack(MBlocksEnum.OrangeBlock.GetBlock(), 1), '2', new ItemStack(MBlocksEnum.BlackBlock.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.TrafficConeSmall, 6), new Object[]{"X1X", "111", "222", '1', new ItemStack(MBlocksEnum.OrangeBlock.GetBlock(), 1), '2', new ItemStack(MBlocksEnum.BlackBlock.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Stoplight, 3), new Object[]{"121", "131", "141", '1', new ItemStack(MBlocksEnum.BlackBlock.GetBlock(), 1), '2', new ItemStack(MBlocks.RedGlow), '3', new ItemStack(MBlocks.YellowGlow), '4', new ItemStack(MBlocks.GreenGlow)});
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.ZincBlock.GetBlock(), new Object[]{true, new Object[]{"FFX", "FFX", "XXX", 'F', "ingotZinc"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.SilverBlock.GetBlock(), new Object[]{true, new Object[]{"FFX", "FFX", "XXX", 'F', "ingotSilver"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.CopperBlock.GetBlock(), new Object[]{true, new Object[]{"FFX", "FFX", "XXX", 'F', "ingotCopper"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.SteelBlock.GetBlock(), new Object[]{true, new Object[]{"FFX", "FFX", "XXX", 'F', "ingotSteel"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.AluminumBlock.GetBlock(), new Object[]{true, new Object[]{"FFX", "FFX", "XXX", 'F', "ingotAluminum"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.AluminumSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotAluminum", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SteelSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotSteel", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.CopperSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotCopper", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SilverSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotSilver", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.ZincSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotZinc", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.AluminumPickaxe, new Object[]{true, new Object[]{"FFF", "X1X", "X1X", 'F', "ingotAluminum", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SteelPickaxe, new Object[]{true, new Object[]{"FFF", "X1X", "X1X", 'F', "ingotSteel", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.CopperPickaxe, new Object[]{true, new Object[]{"FFF", "X1X", "X1X", 'F', "ingotCopper", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SilverPickaxe, new Object[]{true, new Object[]{"FFF", "X1X", "X1X", 'F', "ingotSilver", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.ZincPickaxe, new Object[]{true, new Object[]{"FFF", "X1X", "X1X", 'F', "ingotZinc", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.AluminumHoe, new Object[]{true, new Object[]{"FFX", "X1X", "X1X", 'F', "ingotAluminum", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SteelHoe, new Object[]{true, new Object[]{"FFx", "X1X", "X1X", 'F', "ingotSteel", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.CopperHoe, new Object[]{true, new Object[]{"FFX", "X1X", "X1X", 'F', "ingotCopper", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SilverHoe, new Object[]{true, new Object[]{"FFX", "X1X", "X1X", 'F', "ingotSilver", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.ZincHoe, new Object[]{true, new Object[]{"FFX", "X1X", "X1X", 'F', "ingotZinc", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.AluminumSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotAluminum", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SteelSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotSteel", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.CopperSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotCopper", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SilverSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotSilver", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.ZincSword, new Object[]{true, new Object[]{"XFX", "XFX", "X1X", 'F', "ingotZinc", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.AluminumShovel, new Object[]{true, new Object[]{"XFX", "X1X", "X1X", 'F', "ingotAluminum", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SteelShovel, new Object[]{true, new Object[]{"XFX", "X1X", "X1X", 'F', "ingotSteel", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.CopperShovel, new Object[]{true, new Object[]{"XFX", "X1X", "X1X", 'F', "ingotCopper", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SilverShovel, new Object[]{true, new Object[]{"XFX", "X1X", "X1X", 'F', "ingotSilver", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.ZincShovel, new Object[]{true, new Object[]{"XFX", "X1X", "X1X", 'F', "ingotZinc", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.AluminumAxe, new Object[]{true, new Object[]{"FFX", "F1X", "X1X", 'F', "ingotAluminum", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SteelAxe, new Object[]{true, new Object[]{"FFX", "F1X", "X1X", 'F', "ingotSteel", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.CopperAxe, new Object[]{true, new Object[]{"FFX", "F1X", "X1X", 'F', "ingotCopper", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.SilverAxe, new Object[]{true, new Object[]{"FFX", "F1X", "X1X", 'F', "ingotSilver", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.ZincAxe, new Object[]{true, new Object[]{"FFX", "F1X", "X1X", 'F', "ingotZinc", '1', Items.stick}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocks.WoodTable, new Object[]{true, new Object[]{"FFF", "FXF", "FXF", 'F', "plankWood"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.BlackBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeBlack", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.BlueBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeBlue", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.BrownBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeBrown", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.CyanBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeCyan", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.GrayBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeGray", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.GreenBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeGreen", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.Lblue.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeLightBlue", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.Lgray.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeLightGray", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.LimeBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeLime", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.MagentaBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeMagenta", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.OrangeBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeOrange", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.PinkBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyePink", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.PurpleBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyePurple", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.RedBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeRed", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.WhiteBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeWhite", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.YellowBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeYellow", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.FleshBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeFlesh", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.RainbowBlock.GetBlock(), new Object[]{true, new Object[]{"FBX", "CFX", "XXX", 'B', "dyeRainbow", 'F', "plankWood", 'C', Items.paper}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.BlackDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassBlack"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.BlueDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassBlue"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.BrownDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassBrown"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.CyanDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassCyan"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.GrayDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlasGray"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.GreenDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassGreen"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.LblueDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassLightBlue"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.LgrayDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassLightGray"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.LimeDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassLime"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.MagentaDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassMagenta"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.OrangeDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassOrange"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.PinkDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassPink"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.PurpleDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassPurple"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.RedDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassRed"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.WhiteDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassWhite"}}));
      GameRegistry.addRecipe(new ShapedOreRecipe(MItems.YellowDoorItem, new Object[]{true, new Object[]{"FFX", "FFX", "FFX", 'F', "blockGlassYellow"}}));
      //GameRegistry.addRecipe(new ShapedOreRecipe(MBlocksEnum.AluminumFence, new Object[]{true, new Object[]{"XXX", "FFF", "FFF", 'F', "ingotAluminum"}}));
      GameRegistry.addRecipe(new ItemStack(MBlocks.StoneLantern, 1), new Object[]{"X1X", "X2X", "X1X", '1', new ItemStack(Blocks.cobblestone, 1), '2', new ItemStack(Blocks.glowstone)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StoneFence, 6), new Object[]{"XXX", "111", "111", '1', new ItemStack(Blocks.stone, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.OrangePole, 3), new Object[]{"X1X", "X1X", "X1X", '1', new ItemStack(MBlocksEnum.OrangeBlock.GetBlock(), 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 0), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 1), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 4)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 2), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 6)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 3), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 3)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 4), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 8)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 5), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 2)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 6), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 12)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 7), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 7)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 8), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 10)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 9), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 13)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 10), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 14)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 11), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 9)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 12), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 5)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 13), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 1)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 14), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 11)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.Fence, 1, 15), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(Items.dye, 1, 15)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 0), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.BlackGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 1), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.BlueGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 2), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.CyanGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 3), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.BrownGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 4), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.GrayGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 5), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.GreenGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 6), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.LblueGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 7), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.LgrayGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 8), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.LimeGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 9), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.MagentaGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 10), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.OrangeGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 11), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.PinkGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 12), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.PurpleGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 13), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.RedGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 14), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.YellowGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.GlowstoneFence, 6, 15), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.WhiteGlowstone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 0), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 0), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 1), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 4), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 2), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 6), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 3), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 3), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 4), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 8), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 5), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 2), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 6), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 12), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 7), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 7), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 8), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 10), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 9), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 13), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 10), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 14), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 11), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 9), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 12), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 5), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 13), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 1), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 14), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 11), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocksEnum.colorStone.GetBlock(), 1, 15), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 15), 'B', new ItemStack(Blocks.cobblestone)});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 0), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.BlackStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 1), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.BlueStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 2), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.CyanStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 3), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.BrownStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 4), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.GrayStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 5), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.GreenStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 6), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.Lbluestone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 7), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.LgrayStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 8), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.LimeStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 9), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.MagentaStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 10), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.OrangeStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 11), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.PinkStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 12), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.PurpleStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 13), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.RedStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 14), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.YellowStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.StainedStoneFence, 6, 15), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.WhiteStone.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 0), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.BlackPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 1), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.BluePlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 2), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.CyanPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 3), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.BrownPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 4), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.GrayPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 5), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.GreenPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 6), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.Lblueplanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 7), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.Lgrayplanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 8), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.LimePlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 9), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.MagentaPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 10), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.OrangePlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 11), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.PinkPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 12), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.PurplePlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 13), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.RedPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 14), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.YellowPlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.PlankFence, 6, 15), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.WhitePlanks.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 0), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.BlackIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 1), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.BlueIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 2), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.CyanIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 3), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.BrownIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 4), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.GrayIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 5), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.GreenIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 6), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.LblueIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 7), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.LgrayIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 8), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.LimeIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 9), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack (MBlocksEnum.MagentaIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 10), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.OrangeIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 11), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.PinkIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 12), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.PurpleIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 13), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.RedIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 14), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.YellowIron.GetBlock())});
      GameRegistry.addRecipe(new ItemStack(MBlocks.IronFence, 6, 15), new Object[]{"AAA", "XXX", "XXX", 'X', new ItemStack(MBlocksEnum.WhiteIron.GetBlock())});
      
      Block roughPlastic = MBlocksEnum.roughplastic.GetBlock();
      Block colorPlastic = MBlocksEnum.colorplastic.GetBlock();
      
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 0), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 0), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 1), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 4), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 2), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 6), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 3), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 3), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 4), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 8), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 5), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 2), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 6), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 12), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 7), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 7), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 8), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 10), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 9), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 13), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 10), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 14), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 11), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 9), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 12), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 5), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 13), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 1), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 14), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 11), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(colorPlastic, 1, 15), new Object[]{"XAX", "XBX", "XXX", 'A', new ItemStack(Items.dye, 1, 15), 'B', new ItemStack(roughPlastic)});
      GameRegistry.addRecipe(new ItemStack(roughPlastic, 1), new Object[]{"XXX", "XXX", "XXX", 'X', new ItemStack(MItems.PointlessItem)});
      GameRegistry.addRecipe(new ItemStack(MItems.Donut, 3), new Object[]{"XXX", "YYY", "XXX", 'X', new ItemStack(Items.sugar), 'Y', new ItemStack(Items.bread)});
      GameRegistry.addRecipe(new ItemStack(MItems.Coffee, 1), new Object[]{"XcX", "YzY", "XXX", 'c', new ItemStack(Blocks.cocoa), 'y', new ItemStack(Items.water_bucket)});
      GameRegistry.addRecipe(new ItemStack(MItems.AirRaidSiren, 3), new Object[]{"XXX", "YZY", "XXX", 'Y', new ItemStack(Items.iron_ingot), 'Z', new ItemStack(Blocks.noteblock)});
      GameRegistry.addRecipe(new ItemStack(MItems.Bullet, 25), new Object[]{"XXX", "X7X", "X7X", '6', new ItemStack(Blocks.stone, 1), '7', new ItemStack(Items.iron_ingot, 1)});
   }
}
