package com.monoblocks;

import com.bidahochi.BlockMod.blocks.roadpaints.ScrollingItemBlock;
import com.monoblocks.blocks.signage.AddedLaneSign;
import com.monoblocks.blocks.signage.BlueNameSign;
import com.monoblocks.blocks.signage.BlueNameSignItem;
import com.monoblocks.blocks.signage.BusinessRteSign;
import com.monoblocks.blocks.signage.CattleguardSign;
import com.monoblocks.blocks.signage.ConstructionSign;
import com.monoblocks.blocks.signage.CrossroadSign;
import com.monoblocks.blocks.signage.CrosswalkLight;
import com.monoblocks.blocks.signage.CrosswalkSign;
import com.monoblocks.blocks.signage.DoNotEnterNoPost;
import com.monoblocks.blocks.signage.DoNotEnterSign;
import com.monoblocks.blocks.signage.cardinaldirectionsigns.EastSign;
import com.monoblocks.blocks.signage.EndsSign;
import com.monoblocks.blocks.signage.FourWaySign;
import com.monoblocks.blocks.signage.GasSign;
import com.monoblocks.blocks.signage.GravelRoad;
import com.monoblocks.blocks.signage.GreenNameSign;
import com.monoblocks.blocks.signage.GreenNameSignItem;
import com.monoblocks.blocks.signage.GreenSign;
import com.monoblocks.blocks.signage.GreenSignItem;
import com.monoblocks.blocks.signage.hwysign.*;
import com.monoblocks.blocks.signage.JunctionSign;
import com.monoblocks.blocks.signage.KeepRightSign;
import com.monoblocks.blocks.signage.kmwarn.Km20Warn;
import com.monoblocks.blocks.signage.kmwarn.Km30Warn;
import com.monoblocks.blocks.signage.kmwarn.Km40Warn;
import com.monoblocks.blocks.signage.kmwarn.Km50Warn;
import com.monoblocks.blocks.signage.kmwarn.Km60Warn;
import com.monoblocks.blocks.signage.kmwarn.Km70Warn;
import com.monoblocks.blocks.signage.kmwarn.Km80Warn;
import com.monoblocks.blocks.signage.KmSignA;
import com.monoblocks.blocks.signage.KmSignANoPost;
import com.monoblocks.blocks.signage.KmSignB;
import com.monoblocks.blocks.signage.KmSignBNoPost;
import com.monoblocks.blocks.signage.KmSignC;
import com.monoblocks.blocks.signage.KmSignCNoPost;
import com.monoblocks.blocks.signage.KmSignD;
import com.monoblocks.blocks.signage.KmSignDNoPost;
import com.monoblocks.blocks.signage.KmSignE;
import com.monoblocks.blocks.signage.KmSignENoPost;
import com.monoblocks.blocks.signage.KmSignF;
import com.monoblocks.blocks.signage.KmSignFNoPost;
import com.monoblocks.blocks.signage.KmSignG;
import com.monoblocks.blocks.signage.KmSignGNoPost;
import com.monoblocks.blocks.signage.KmSignH;
import com.monoblocks.blocks.signage.KmSignHNoPost;
import com.monoblocks.blocks.signage.KmSignI;
import com.monoblocks.blocks.signage.KmSignINoPost;
import com.monoblocks.blocks.signage.KmSignJ;
import com.monoblocks.blocks.signage.KmSignJNoPost;
import com.monoblocks.blocks.signage.KmSignK;
import com.monoblocks.blocks.signage.KmSignKNoPost;
import com.monoblocks.blocks.signage.KmSignL;
import com.monoblocks.blocks.signage.KmSignLNoPost;
import com.monoblocks.blocks.signage.LaneEnds;
import com.monoblocks.blocks.signage.LeftAddedLane;
import com.monoblocks.blocks.signage.LeftArrow;
import com.monoblocks.blocks.signage.LeftCorner;
import com.monoblocks.blocks.signage.LeftCurve;
import com.monoblocks.blocks.signage.LeftDoubleCurveSign;
import com.monoblocks.blocks.signage.LeftLaneEnds;
import com.monoblocks.blocks.signage.LeftObstruction;
import com.monoblocks.blocks.signage.LeftSharpCornerSign;
import com.monoblocks.blocks.signage.LeftSideRoad;
import com.monoblocks.blocks.signage.LeftSign;
import com.monoblocks.blocks.signage.LeftTurnSign;
import com.monoblocks.blocks.signage.LitteringPenalty;
import com.monoblocks.blocks.signage.NarrowBridge;
import com.monoblocks.blocks.signage.NarrowRoad;
import com.monoblocks.blocks.signage.NoExit;
import com.monoblocks.blocks.signage.NoLeftTurn;
import com.monoblocks.blocks.signage.NoParking;
import com.monoblocks.blocks.signage.NoRightTurn;
import com.monoblocks.blocks.signage.cardinaldirectionsigns.NorthSign;
import com.monoblocks.blocks.signage.OpeningBridge;
import com.monoblocks.blocks.signage.RailwayCrossing;
import com.monoblocks.blocks.signage.RightArrow;
import com.monoblocks.blocks.signage.RightCorner;
import com.monoblocks.blocks.signage.RightCurve;
import com.monoblocks.blocks.signage.RightDoubleCurveSign;
import com.monoblocks.blocks.signage.RightObstruction;
import com.monoblocks.blocks.signage.RightSharpCornerSign;
import com.monoblocks.blocks.signage.RightSideRoad;
import com.monoblocks.blocks.signage.RightSign;
import com.monoblocks.blocks.signage.RightTurnRedSign;
import com.monoblocks.blocks.signage.RightTurnSign;
import com.monoblocks.blocks.signage.RoundaboutSign;
import com.monoblocks.blocks.signage.cardinaldirectionsigns.SouthSign;
import com.monoblocks.blocks.signage.StopSign;
import com.monoblocks.blocks.signage.StopSignAhead;
import com.monoblocks.blocks.signage.StopSignNoPost;
import com.monoblocks.blocks.signage.StraightSign;
import com.monoblocks.blocks.signage.ThreeWaySign;
import com.monoblocks.blocks.signage.ToSign;
import com.monoblocks.blocks.signage.TrafficLightSign;
import com.monoblocks.blocks.signage.TrainCrossingSign;
import com.monoblocks.blocks.signage.TunnelSign;
import com.monoblocks.blocks.signage.cardinaldirectionsigns.WestSign;
import com.monoblocks.blocks.signage.WhiteSign;
import com.monoblocks.blocks.signage.WhiteSignItem;
import com.monoblocks.blocks.signage.WindingRoadSign;
import com.monoblocks.blocks.signage.YieldSign;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.item.Item;

public class SignReg {
   public static Block BlueNameSign;
   public static Block GreenNameSign;
   public static Block GreenSign;
   public static Block StopSign;
   public static Block GravelRoad;
   public static Block KmSignA;
   public static Block KmSignB;
   public static Block KmSignC;
   public static Block KmSignD;
   public static Block KmSignE;
   public static Block TrafficLightSign;
   public static Block DoNotEnterSign;
   public static Block WindingRoad;
   public static Block OpeningBridge;
   public static Block NoExit;
   public static Block LaneEnds;
   public static Block RailwayCrossing;
   public static Block NarrowBridge;
   public static Block RightArrow;
   public static Block LeftArrow;
   public static Block KmSignF;
   public static Block KmSignG;
   public static Block KmSignH;
   public static Block KmSignI;
   public static Block NoParking;
   public static Block RightCorner;
   public static Block LeftCorner;
   public static Block Hwy1;
   public static Block Hwy2;
   public static Block Hwy3;
   public static Block Hwy3A;
   public static Block Hwy4;
   public static Block Hwy5;
   public static Block Hwy6;
   public static Block Hwy7;
   public static Block Hwy8;
   public static Block Hwy9;
   public static Block Hwy10;
   public static Block Hwy20;
   public static Block Hwy37;
   public static Block Hwy21;
   public static Block Hwy91;
   public static Block Hwy93;
   public static Block Hwy95;
   public static Block Hwy97;
   public static Block Hwy99;
   public static Block Crosswalk;
   public static Block TrainCrossing;
   public static Block StopAhead;
   public static Block Yield;
   public static Block Construction;
   public static Block North;
   public static Block South;
   public static Block East;
   public static Block West;
   public static Block LeftSharpCorner;
   public static Block RightSharpCorner;
   public static Block WhiteSign;
   public static Item WhiteSignItem;
   public static Item GreenSignItem;
   public static Item BlueNameSignItem;
   public static Item GreenNameSignItem;
   public static Block Roundabout;
   public static Block AddedLane;
   public static Block CattleguardSign;
   public static Block KmSignJ;
   public static Block Littering;
   public static Block NoRightTurn;
   public static Block NoLeftTurn;
   public static Block Straight;
   public static Block Left;
   public static Block Right;
   public static Block To;
   public static Block Junction;
   public static Block Ends;
   public static Block Tunnel;
   public static Block RightObstruction;
   public static Block LeftObstruction;
   public static Block RightCurve;
   public static Block LeftCurve;
   public static Block RightDoubleCurve;
   public static Block LeftDoubleCurve;
   public static Block Crossroad;
   public static Block RightSideRoad;
   public static Block LeftSideRoad;
   public static Block Km80Warn;
   public static Block Km70Warn;
   public static Block Km60Warn;
   public static Block Km50Warn;
   public static Block Km40Warn;
   public static Block Km30Warn;
   public static Block Km20Warn;
   public static Block LeftLaneEnds;
   public static Block NarrowRoad;
   public static Block KeepRightDivider;
   public static Block StopSignNoPost;
   public static Block DoNotEnterNoPost;
   public static Block KmSignANoPost;
   public static Block KmSignBNoPost;
   public static Block KmSignCNoPost;
   public static Block KmSignDNoPost;
   public static Block KmSignENoPost;
   public static Block KmSignFNoPost;
   public static Block KmSignGNoPost;
   public static Block KmSignHNoPost;
   public static Block KmSignINoPost;
   public static Block KmSignJNoPost;
   public static Block LeftAddedLane;
   public static Block Hwy11;
   public static Block Hwy12;
   public static Block Hwy13;
   public static Block Hwy15;
   public static Block Hwy9A;
   public static Block RightTurn;
   public static Block LeftTurn;
   public static Block Hwy14;
   public static Block Hwy16;
   public static Block Hwy17;
   public static Block Hwy18;
   public static Block Hwy19;
   public static Block Hwy22;
   public static Block Hwy23;
   public static Block Hwy24;
   public static Block Hwy25;
   public static Block Hwy26;
   public static Block Hwy27;
   public static Block Hwy28;
   public static Block Hwy29;
   public static Block Hwy30;
   public static Block Hwy31;
   public static Block Hwy32;
   public static Block Hwy33;
   public static Block Hwy34;
   public static Block Hwy35;
   public static Block Hwy36;
   public static Block Hwy38;
   public static Block Hwy39;
   public static Block Hwy40;
   public static Block KmSignK;
   public static Block KmSignL;
   public static Block KmSignKNoPost;
   public static Block KmSignLNoPost;
   public static Block BusinessRoute;
   public static Block Gas;
   public static Block FourWay;
   public static Block ThreeWay;
   public static Block RightTurnRed;
   public static Block CrosswalkLight;

   public SignReg() {
      Hwy1 = (new Hwy1Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy2 = (new Hwy2Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy3 = (new Hwy3Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy3A = (new Hwy3ASign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy4 = (new Hwy4Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy5 = (new Hwy5Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy6 = (new Hwy6Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy7 = (new Hwy7Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy8 = (new Hwy8Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy9 = (new Hwy9Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy10 = (new Hwy10Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy20 = (new Hwy20Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy37 = (new Hwy37Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy21 = (new Hwy21Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy91 = (new Hwy91Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy93 = (new Hwy93Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy95 = (new Hwy95Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy97 = (new Hwy97Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy99 = (new Hwy99Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy11 = (new Hwy11Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignA = (new KmSignA()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignB = (new KmSignB()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignC = (new KmSignC()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignD = (new KmSignD()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignE = (new KmSignE()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignF = (new KmSignF()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignG = (new KmSignG()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignH = (new KmSignH()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignI = (new KmSignI()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignJ = (new KmSignJ()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      AddedLane = (new AddedLaneSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Littering = (new LitteringPenalty()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      CattleguardSign = (new CattleguardSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      TrafficLightSign = (new TrafficLightSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      DoNotEnterSign = (new DoNotEnterSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      WindingRoad = (new WindingRoadSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      OpeningBridge = (new OpeningBridge()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      NoExit = (new NoExit()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LaneEnds = (new LaneEnds()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      NarrowBridge = (new NarrowBridge()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RailwayCrossing = (new RailwayCrossing()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightArrow = (new RightArrow()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LeftArrow = (new LeftArrow()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightCorner = (new RightCorner()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LeftCorner = (new LeftCorner()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      GravelRoad = (new GravelRoad()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      NoParking = (new NoParking()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      StopSign = (new StopSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Crosswalk = (new CrosswalkSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      TrainCrossing = (new TrainCrossingSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      StopAhead = (new StopSignAhead()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Yield = (new YieldSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Construction = (new ConstructionSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      North = (new NorthSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      South = (new SouthSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      East = (new EastSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      West = (new WestSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightSharpCorner = (new RightSharpCornerSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LeftSharpCorner = (new LeftSharpCornerSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      WhiteSign = new WhiteSign();
      GreenSign = new GreenSign();
      BlueNameSign = new BlueNameSign();
      BlueNameSignItem = new BlueNameSignItem();
      WhiteSignItem = new WhiteSignItem();
      GreenSignItem = new GreenSignItem();
      GreenNameSign = new GreenNameSign();
      GreenNameSignItem = new GreenNameSignItem();
      NoRightTurn = (new NoRightTurn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      NoLeftTurn = (new NoLeftTurn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Straight = (new StraightSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Left = (new LeftSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Right = (new RightSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      To = (new ToSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Junction = (new JunctionSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Ends = (new EndsSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Tunnel = (new TunnelSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightObstruction = (new RightObstruction()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LeftObstruction = (new LeftObstruction()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LeftCurve = (new LeftCurve()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightCurve = (new RightCurve()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Roundabout = new RoundaboutSign();
      RightDoubleCurve = new RightDoubleCurveSign();
      LeftDoubleCurve = new LeftDoubleCurveSign();
      Crossroad = new CrossroadSign();
      RightSideRoad = new RightSideRoad();
      LeftSideRoad = new LeftSideRoad();
      Km20Warn = (new Km20Warn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Km30Warn = (new Km30Warn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Km40Warn = (new Km40Warn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Km50Warn = (new Km50Warn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Km60Warn = (new Km60Warn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Km70Warn = (new Km70Warn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Km80Warn = (new Km80Warn()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightCurve = (new RightCurve()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightCurve = (new RightCurve()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightCurve = (new RightCurve()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightCurve = (new RightCurve()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightCurve = (new RightCurve()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LeftLaneEnds = (new LeftLaneEnds()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      NarrowRoad = (new NarrowRoad()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KeepRightDivider = (new KeepRightSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      StopSignNoPost = (new StopSignNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      DoNotEnterNoPost = (new DoNotEnterNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignANoPost = (new KmSignANoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignBNoPost = (new KmSignBNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignCNoPost = (new KmSignCNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignDNoPost = (new KmSignDNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignENoPost = (new KmSignENoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignFNoPost = (new KmSignFNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignGNoPost = (new KmSignGNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignHNoPost = (new KmSignHNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignHNoPost = (new KmSignHNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignINoPost = (new KmSignINoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignJNoPost = (new KmSignJNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LeftAddedLane = (new LeftAddedLane()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy11 = (new Hwy11Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy12 = (new Hwy12Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy13 = (new Hwy13Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy15 = (new Hwy15Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy9A = (new Hwy9ASign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightTurn = (new RightTurnSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      LeftTurn = (new LeftTurnSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy14 = (new Hwy14Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy16 = (new Hwy16Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy17 = (new Hwy17Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy18 = (new Hwy18Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy19 = (new Hwy19Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy22 = (new Hwy22Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy23 = (new Hwy23Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy24 = (new Hwy24Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy25 = (new Hwy25Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy26 = (new Hwy26Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy27 = (new Hwy27Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy28 = (new Hwy28Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy29 = (new Hwy29Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy30 = (new Hwy30Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy31 = (new Hwy31Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy32 = (new Hwy32Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy33 = (new Hwy33Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy34 = (new Hwy34Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy35 = (new Hwy35Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy36 = (new Hwy36Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy38 = (new Hwy38Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy39 = (new Hwy39Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Hwy40 = (new Hwy40Sign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignK = (new KmSignK()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignL = (new KmSignL()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignKNoPost = (new KmSignKNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      KmSignLNoPost = (new KmSignLNoPost()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      BusinessRoute = (new BusinessRteSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      Gas = (new GasSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      FourWay = (new FourWaySign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      ThreeWay = (new ThreeWaySign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      RightTurnRed = (new RightTurnRedSign()).setStepSound(Block.soundTypeMetal).setCreativeTab(Monoblocks.monoblocksSignage);
      CrosswalkLight = new CrosswalkLight();
      GameRegistry.registerBlock(Hwy1,  ScrollingItemBlock.class,"Highway 1 Sign");
      GameRegistry.registerBlock(Hwy2,  ScrollingItemBlock.class,"Highway 2 Sign");
      GameRegistry.registerBlock(Hwy3,  ScrollingItemBlock.class,"Highway 3 Sign");
      GameRegistry.registerBlock(Hwy3A, ScrollingItemBlock.class, "Highway 3A Sign");
      GameRegistry.registerBlock(Hwy4,  ScrollingItemBlock.class,"Highway 4 Sign");
      GameRegistry.registerBlock(Hwy5,  ScrollingItemBlock.class,"Highway 5 Sign");
      GameRegistry.registerBlock(Hwy6,  ScrollingItemBlock.class,"Highway 6 Sign");
      GameRegistry.registerBlock(Hwy7,  ScrollingItemBlock.class,"Highway 7 Sign");
      GameRegistry.registerBlock(Hwy8,  ScrollingItemBlock.class,"Highway 8 Sign");
      GameRegistry.registerBlock(Hwy9,  ScrollingItemBlock.class,"Highway 9 Sign");
      GameRegistry.registerBlock(Hwy10, ScrollingItemBlock.class, "Highway 10 Sign");
      GameRegistry.registerBlock(Hwy20, ScrollingItemBlock.class, "Highway 20 Sign");
      GameRegistry.registerBlock(Hwy37, ScrollingItemBlock.class, "Highway 37 Sign");
      GameRegistry.registerBlock(Hwy21, ScrollingItemBlock.class, "Highway 21 Sign");
      GameRegistry.registerBlock(Hwy91, ScrollingItemBlock.class, "Highway 91 Sign");
      GameRegistry.registerBlock(Hwy93, ScrollingItemBlock.class, "Highway 93 Sign");
      GameRegistry.registerBlock(Hwy95, ScrollingItemBlock.class, "Highway 95 Sign");
      GameRegistry.registerBlock(Hwy97, ScrollingItemBlock.class, "Highway 97 Sign");
      GameRegistry.registerBlock(Hwy99, ScrollingItemBlock.class, "Highway 99 Sign");
      GameRegistry.registerBlock(TrafficLightSign, "Traffic Light Sign");
      GameRegistry.registerBlock(AddedLane, "Added Lane Sign");
      GameRegistry.registerBlock(CattleguardSign, "Cattleguard Sign");
      GameRegistry.registerBlock(Littering, "Littering Penalty Sign");
      GameRegistry.registerBlock(KmSignA, ScrollingItemBlock.class, "50 km/h Sign");
      GameRegistry.registerBlock(KmSignB, ScrollingItemBlock.class, "70 km/h Sign");
      GameRegistry.registerBlock(KmSignC, ScrollingItemBlock.class, "80 km/h Sign");
      GameRegistry.registerBlock(KmSignD, ScrollingItemBlock.class, "100 km/h Sign");
      GameRegistry.registerBlock(KmSignE, ScrollingItemBlock.class, "120 km/h Sign");
      GameRegistry.registerBlock(KmSignF, ScrollingItemBlock.class, "30 km/h Sign");
      GameRegistry.registerBlock(KmSignG, ScrollingItemBlock.class, "60 km/h Sign");
      GameRegistry.registerBlock(KmSignH, ScrollingItemBlock.class, "40 km/h Sign");
      GameRegistry.registerBlock(KmSignI, ScrollingItemBlock.class, "90 km/h Sign");
      GameRegistry.registerBlock(KmSignJ, ScrollingItemBlock.class, "110 km/h Sign");
      GameRegistry.registerBlock(KmSignK, ScrollingItemBlock.class, "130 km/h Sign");
      GameRegistry.registerBlock(KmSignL, ScrollingItemBlock.class, "140 km/h Sign");
      GameRegistry.registerBlock(DoNotEnterSign, "Do Not Enter Sign");
      GameRegistry.registerBlock(GravelRoad, "Gravel Road Sign");
      GameRegistry.registerBlock(WindingRoad, "Winding Road Sign");
      GameRegistry.registerBlock(OpeningBridge, "Opening Bridge Sign");
      GameRegistry.registerBlock(NoExit, "No Exit Sign");
      GameRegistry.registerBlock(LaneEnds, "Lane Ends Sign");
      GameRegistry.registerBlock(NarrowBridge, "Narrow Bridge Sign");
      GameRegistry.registerBlock(RailwayCrossing, "Railway Crossing Sign");
      GameRegistry.registerBlock(RightArrow, "Right Arrow Sign");
      GameRegistry.registerBlock(LeftArrow, "Left Arrow Sign");
      GameRegistry.registerBlock(RightCorner, "Right Corner Sign");
      GameRegistry.registerBlock(LeftCorner, "Left Corner Sign");
      GameRegistry.registerBlock(NoParking, "No Parking Sign");
      GameRegistry.registerBlock(StopSign, "Stop Sign");
      GameRegistry.registerBlock(Crosswalk, "Crosswalk Sign");
      GameRegistry.registerBlock(North, ScrollingItemBlock.class, "North Sign");
      GameRegistry.registerBlock(South, ScrollingItemBlock.class, "South Sign");
      GameRegistry.registerBlock(East,  ScrollingItemBlock.class,"East Sign");
      GameRegistry.registerBlock(West,  ScrollingItemBlock.class,"West Sign");
      GameRegistry.registerBlock(TrainCrossing, "TrainCrossing");
      GameRegistry.registerBlock(StopAhead, "StopAhead");
      GameRegistry.registerBlock(Yield, "Yield");
      GameRegistry.registerBlock(Construction, "Construction");
      GameRegistry.registerBlock(RightSharpCorner, "RSharpCorner");
      GameRegistry.registerBlock(LeftSharpCorner, "LSharpCorner");
      GameRegistry.registerBlock(WhiteSign, "whitesign");
      GameRegistry.registerItem(WhiteSignItem, "whiteSign");
      GameRegistry.registerBlock(GreenSign, "greensign");
      GameRegistry.registerItem(GreenSignItem, "GreenSign");
      GameRegistry.registerBlock(BlueNameSign, "bluenamesign");
      GameRegistry.registerItem(BlueNameSignItem, "blueNameSign");
      GameRegistry.registerBlock(GreenNameSign, "greennamesign");
      GameRegistry.registerItem(GreenNameSignItem, "greenNameSign");
      GameRegistry.registerBlock(NoRightTurn, "norightturnsign");
      GameRegistry.registerBlock(NoLeftTurn, "noleftturnsign");
      GameRegistry.registerBlock(Straight, "straight Sign");
      GameRegistry.registerBlock(Left, "left Sign");
      GameRegistry.registerBlock(Right, "right Sign");
      GameRegistry.registerBlock(To, "to Sign");
      GameRegistry.registerBlock(Junction, "junction Sign");
      GameRegistry.registerBlock(Ends, "ends Sign");
      GameRegistry.registerBlock(BusinessRoute, "businessrte");
      GameRegistry.registerBlock(Tunnel, "Tunnel Sign");
      GameRegistry.registerBlock(RightObstruction, "Right Obstruction");
      GameRegistry.registerBlock(LeftObstruction, "Left Obstruction");
      GameRegistry.registerBlock(RightCurve, "Right Curve");
      GameRegistry.registerBlock(LeftCurve, "Left Curve");
      GameRegistry.registerBlock(Roundabout, "Roundabout Sign");
      GameRegistry.registerBlock(RightDoubleCurve, "Right Double Curve Sign");
      GameRegistry.registerBlock(LeftDoubleCurve, "Left Double Curve Sign");
      GameRegistry.registerBlock(Crossroad, "Crossroad Sign");
      GameRegistry.registerBlock(RightSideRoad, "Right Side Road Sign");
      GameRegistry.registerBlock(LeftSideRoad, "Left Side Road Sign");
      GameRegistry.registerBlock(Km80Warn, ScrollingItemBlock.class, "km80warn");
      GameRegistry.registerBlock(Km70Warn, ScrollingItemBlock.class, "km70warn");
      GameRegistry.registerBlock(Km60Warn, ScrollingItemBlock.class, "km60warn");
      GameRegistry.registerBlock(Km50Warn, ScrollingItemBlock.class, "km50warn");
      GameRegistry.registerBlock(Km40Warn, ScrollingItemBlock.class, "km40warn");
      GameRegistry.registerBlock(Km30Warn, ScrollingItemBlock.class, "km30warn");
      GameRegistry.registerBlock(Km20Warn, ScrollingItemBlock.class, "km20warn");
      GameRegistry.registerBlock(LeftLaneEnds, "leftlaneends");
      GameRegistry.registerBlock(NarrowRoad, "narrowroad");
      GameRegistry.registerBlock(KeepRightDivider, "keeprightdivider");
      GameRegistry.registerBlock(StopSignNoPost, "stopsignnopost");
      GameRegistry.registerBlock(DoNotEnterNoPost, "donotenternopost");
      GameRegistry.registerBlock(KmSignANoPost, ScrollingItemBlock.class, "kmsignanopost");
      GameRegistry.registerBlock(KmSignBNoPost, ScrollingItemBlock.class, "kmsignbnopost");
      GameRegistry.registerBlock(KmSignCNoPost, ScrollingItemBlock.class, "kmsigncnopost");
      GameRegistry.registerBlock(KmSignDNoPost, ScrollingItemBlock.class, "kmsigndnopost");
      GameRegistry.registerBlock(KmSignENoPost, ScrollingItemBlock.class, "kmsignenopost");
      GameRegistry.registerBlock(KmSignFNoPost, ScrollingItemBlock.class, "kmsignfnopost");
      GameRegistry.registerBlock(KmSignGNoPost, ScrollingItemBlock.class, "kmsigngnopost");
      GameRegistry.registerBlock(KmSignHNoPost, ScrollingItemBlock.class, "kmsignhnopost");
      GameRegistry.registerBlock(KmSignINoPost, ScrollingItemBlock.class, "kmsignInopost");
      GameRegistry.registerBlock(KmSignJNoPost, ScrollingItemBlock.class, "kmsignJnopost");
      GameRegistry.registerBlock(KmSignKNoPost, ScrollingItemBlock.class, "kmsignknopost");
      GameRegistry.registerBlock(KmSignLNoPost, ScrollingItemBlock.class, "kmsignlnopost");
      GameRegistry.registerBlock(LeftAddedLane, ScrollingItemBlock.class, "leftaddedlane");
      GameRegistry.registerBlock(ThreeWay, "3way");
      GameRegistry.registerBlock(FourWay, "4way");
      GameRegistry.registerBlock(Gas, "gas");
      GameRegistry.registerBlock(RightTurnRed, "rightturnred");
      GameRegistry.registerBlock(CrosswalkLight, "crosswalklight");
      GameRegistry.registerBlock(Hwy11, ScrollingItemBlock.class,"hwy11");
      GameRegistry.registerBlock(Hwy12, ScrollingItemBlock.class,"hwy12");
      GameRegistry.registerBlock(Hwy13, ScrollingItemBlock.class,"hwy13");
      GameRegistry.registerBlock(Hwy15, ScrollingItemBlock.class,"hwy15");
      GameRegistry.registerBlock(Hwy9A, ScrollingItemBlock.class,"hwy9a");
      GameRegistry.registerBlock(RightTurn, "rturn");
      GameRegistry.registerBlock(LeftTurn, "lturn");
      GameRegistry.registerBlock(Hwy14, ScrollingItemBlock.class, "hwy14");
      GameRegistry.registerBlock(Hwy16, ScrollingItemBlock.class, "hwy16");
      GameRegistry.registerBlock(Hwy17, ScrollingItemBlock.class, "hwy17");
      GameRegistry.registerBlock(Hwy18, ScrollingItemBlock.class, "hwy18");
      GameRegistry.registerBlock(Hwy19, ScrollingItemBlock.class, "hwy19");
      GameRegistry.registerBlock(Hwy22, ScrollingItemBlock.class, "hwy22");
      GameRegistry.registerBlock(Hwy23, ScrollingItemBlock.class, "hwy23");
      GameRegistry.registerBlock(Hwy24, ScrollingItemBlock.class, "hwy24");
      GameRegistry.registerBlock(Hwy25, ScrollingItemBlock.class, "hwy25");
      GameRegistry.registerBlock(Hwy26, ScrollingItemBlock.class, "hwy26");
      GameRegistry.registerBlock(Hwy27, ScrollingItemBlock.class, "hwy27");
      GameRegistry.registerBlock(Hwy28, ScrollingItemBlock.class, "hwy28");
      GameRegistry.registerBlock(Hwy29, ScrollingItemBlock.class, "hwy29");
      GameRegistry.registerBlock(Hwy30, ScrollingItemBlock.class, "hwy30");
      GameRegistry.registerBlock(Hwy31, ScrollingItemBlock.class, "hwy31");
      GameRegistry.registerBlock(Hwy32, ScrollingItemBlock.class, "hwy32");
      GameRegistry.registerBlock(Hwy33, ScrollingItemBlock.class, "hwy33");
      GameRegistry.registerBlock(Hwy34, ScrollingItemBlock.class, "hwy34");
      GameRegistry.registerBlock(Hwy35, ScrollingItemBlock.class, "hwy35");
      GameRegistry.registerBlock(Hwy36, ScrollingItemBlock.class, "hwy36");
      GameRegistry.registerBlock(Hwy38, ScrollingItemBlock.class, "hwy38");
      GameRegistry.registerBlock(Hwy39, ScrollingItemBlock.class, "hwy39");
      GameRegistry.registerBlock(Hwy40, ScrollingItemBlock.class, "hwy40");
   }
}
