package com.monoblocks.proxy;

import com.jadarstudios.developercapes.DevCapes;
import com.monoblocks.ChestReg;
import com.monoblocks.FenceRender;
import com.monoblocks.MBlocks;
import com.monoblocks.blocks.models.ModelBaconPig;
import com.monoblocks.blocks.signage.tileentity.*;
import com.monoblocks.blocks.tileentity.*;
import com.monoblocks.entities.BaconPigEntity;
import com.monoblocks.renderer.*;
import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.client.registry.RenderingRegistry;
import net.minecraft.item.Item;
import net.minecraftforge.client.MinecraftForgeClient;

public class ClientProxy extends CommonProxy {
   public void registerRenderThings() {
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityWoodTable.class, new RenderWoodTable());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.WoodTable), new ItemRenderWoodTable(new RenderWoodTable(), new TileEntityWoodTable()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntitySifter.class, new SifterRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.Sifter), new ItemSifterRenderer(new SifterRenderer(), new TileEntitySifter()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFryer.class, new FryerRenderer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStoplight.class, new StoplightRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.Stoplight), new ItemStoplightRenderer(new StoplightRenderer(), new TileEntityStoplight()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRoundBBQ.class, new RoundBBQRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.RoundBBQ), new ItemStoplightRenderer(new RoundBBQRenderer(), new TileEntityRoundBBQ()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRedLight.class, new RedLightRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.RedLight), new ItemStoplightRenderer(new RedLightRenderer(), new TileEntityRedLight()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStoneChest.class, new StoneChestRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(ChestReg.StoneChest), new ItemRenderStoneChest());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficCone.class, new TrafficConeRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.TrafficCone), new ItemStoplightRenderer(new TrafficConeRenderer(), new TileEntityTrafficCone()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficConeSmall.class, new TrafficConeSmallRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.TrafficConeSmall), new ItemStoplightRenderer(new TrafficConeSmallRenderer(), new TileEntityTrafficConeSmall()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStopSign.class, new StopSignRenderer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityOrangePost.class, new OrangePoleRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.OrangePole), new ItemRenderOrangePole(new OrangePoleRenderer(), new TileEntityOrangePost()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntitySafetyPost.class, new SafetyPoleRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.SafetyPole), new ItemRenderSafetyPole(new SafetyPoleRenderer(), new TileEntitySafetyPost()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStoneLantern.class, new StoneLanternRenderer());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.StoneLantern), new ItemRenderSafetyPole(new StoneLanternRenderer(), new TileEntityStoneLantern()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGravelRoad.class, new GravelRoadRenderer());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficLightSign.class, new TrafficLightSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignA.class, new KmSignARender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignB.class, new KmSignBRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignC.class, new KmSignCRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignD.class, new KmSignDRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignE.class, new KmSignERender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityDoNotEnterSign.class, new DoNotEnterSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityWindingRoad.class, new WindingRoadRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityOpeningBridge.class, new OpeningBridgeRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityNoExit.class, new NoExitRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLaneEnds.class, new LaneEndsRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityNarrowBridge.class, new NarrowBridgeRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRailwayCrossing.class, new RailwayCrossingRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRightArrow.class, new RightArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftArrow.class, new LeftArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignF.class, new KmSignFRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignG.class, new KmSignGRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignH.class, new KmSignHRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignI.class, new KmSignIRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntitySingleStoplight.class, new SingleStoplightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityNoParking.class, new NoParkingRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRightCorner.class, new RightCornerRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftCorner.class, new LeftCornerRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign.class, new Hwy1Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign2.class, new Hwy2Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign3.class, new Hwy3Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign3A.class, new Hwy3ARender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign4.class, new Hwy4Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign5.class, new Hwy5Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign6.class, new Hwy6Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign7.class, new Hwy7Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign8.class, new Hwy8Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign9.class, new Hwy9Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign10.class, new Hwy10Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign20.class, new Hwy20Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign37.class, new Hwy37Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStoplightPole.class, new StoplightPoleRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityNorthSign.class, new NorthRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntitySouthSign.class, new RenderSouth());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityEastSign.class, new EastRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityWestSign.class, new WestSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGate.class, new GateRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGateClosed.class, new GateClosedRender());
      RenderingRegistry.registerBlockHandler(new FenceRender());
      RenderingRegistry.registerEntityRenderingHandler(BaconPigEntity.class, new BaconPigRender(new ModelBaconPig(), new ModelBaconPig(0.5F), 0.4F));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFlag.class, new FlagRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYellowStoplight.class, new YellowStoplightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYellowStoplightPole.class, new YellowStoplightPoleRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCrosswalkSign.class, new CrosswalkRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStreetLight.class, new StreetLightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign21.class, new Hwy21Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign91.class, new Hwy91Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign93.class, new Hwy93Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign95.class, new Hwy95Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign97.class, new Hwy97Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwySign99.class, new Hwy99Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStereo.class, new StereoRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBlackLamp.class, new BlackLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBlueLamp.class, new BlueLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBrownLamp.class, new BrownLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCyanLamp.class, new CyanLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGrayLamp.class, new GrayLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGreenLamp.class, new GreenLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLblueLamp.class, new LblueLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLgrayLamp.class, new LgrayLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLimeLamp.class, new LimeLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityMagentaLamp.class, new MagentaLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityOrangeLamp.class, new OrangeLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPinkLamp.class, new PinkLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPurpleLamp.class, new PurpleLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRedLamp.class, new RedLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityWhiteLamp.class, new WhiteLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYellowLamp.class, new YellowLampRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGuardRail.class, new GuardRailRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityDoubleStreetLight.class, new DoubleStreetLightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityInsideGuardRail.class, new InsideGuardRailRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityOutsideGuardRail.class, new OutsideGuardRailRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrainCrossing.class, new TrainCrossingRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStopAhead.class, new StopAheadRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYield.class, new YieldRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityConstruction.class, new ConstructionSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftSharpCorner.class, new LeftSharpCornerRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntitySharpCorner.class, new RightSharpCornerRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityShowcase.class, new ShowcaseRender());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.Showcase), new ItemRenderShowcase(new ShowcaseRender(), new TileEntityShowcase()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCDPlayer.class, new CDPlayerRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityWhiteSign.class, new WhiteSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGreenSign.class, new GreenSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBlueNameSign.class, new BlueNameSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGreenNameSign.class, new GreenNameSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCattleguardSign.class, new CattleguardRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityAddedLane.class, new RenderAddedLane());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLittering.class, new LitteringPenaltyRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignJ.class, new KmSignJRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYellowReflector.class, new YellowReflectorRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityNoRightTurn.class, new NoRightTurnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityNoLeftTurn.class, new NoLeftTurnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole1.class, new PowerPole1Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole2.class, new PowerPole2Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole3.class, new PowerPole3Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole4.class, new PowerPole4Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole5.class, new PowerPole5Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole6.class, new PowerPole6Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole7.class, new PowerPole7Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole8.class, new PowerPole8Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole9.class, new PowerPole9Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole10.class, new PowerPole10Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole11.class, new PowerPole11Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole12.class, new PowerPole12Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole13.class, new PowerPole13Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTransformer.class, new TransformerRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityInsulator1.class, new Insulator1Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityInsulator2.class, new Insulator2Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole14.class, new PowerPole14Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityShoplight.class, new ShoplightRender());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.Shoplight), new ItemRenderSafetyPole(new ShoplightRender(), new TileEntityShoplight()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityOrangeShoplight.class, new OrangeShoplightRender());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.OrangeShoplight), new ItemRenderSafetyPole(new OrangeShoplightRender(), new TileEntityOrangeShoplight()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStraight.class, new StraightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeft.class, new LeftRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRight.class, new RightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTo.class, new ToRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityJunction.class, new JunctionRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityEnds.class, new EndsRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTunnelAhead.class, new TunnelRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStoplightPoleAttachment.class, new StoplightPoleAttachmentRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYellowStoplightStick.class, new YellowStoplightStickRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStreetLightPole.class, new StreetlightPoleRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRightObstruction.class, new RightObstructionRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftObstruction.class, new LeftObstructionRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole15.class, new PowerPole15Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftCurve.class, new LeftCurveRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRightCurve.class, new RightCurveRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityIronLantern.class, new IronLanternRender());
      MinecraftForgeClient.registerItemRenderer(Item.getItemFromBlock(MBlocks.IronLantern), new ItemRenderSafetyPole(new IronLanternRender(), new TileEntityIronLantern()));
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGroundConnector.class, new RenderGroundConnector());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole16.class, new PowerPole16Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRoundabout.class, new RoundaboutRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRightDoubleCurve.class, new RightDoubleCurveRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftDoubleCurve.class, new LeftDoubleCurveRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCrossroad.class, new CrossroadRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRightSideRoad.class, new RightSideRoadRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftSideRoad.class, new LeftSideRoadRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole17.class, new PowerPole17Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPowerPole18.class, new PowerPole18Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKm80Warn.class, new Km80WarnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKm70Warn.class, new Km70WarnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKm60Warn.class, new Km60WarnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKm50Warn.class, new Km50WarnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKm40Warn.class, new Km40WarnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKm30Warn.class, new Km30WarnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKm20Warn.class, new Km20WarnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftLaneEnds.class, new LeftLaneEndsRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityNarrowRoad.class, new NarrowRoadRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKeepRightDivider.class, new KeepRightDividerRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityStopSignNoPost.class, new StopSignNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityDoNotEnterNoPost.class, new DoNotEnterNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignANoPost.class, new KmSignANoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignBNoPost.class, new KmSignBNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignCNoPost.class, new KmSignCNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignDNoPost.class, new KmSignDNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignENoPost.class, new KmSignENoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignFNoPost.class, new KmSignFNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignGNoPost.class, new KmSignGNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignHNoPost.class, new KmSignHNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignINoPost.class, new KmSignINoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignJNoPost.class, new KmSignJNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignKNoPost.class, new KmSignKNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignLNoPost.class, new KmSignLNoPostRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignK.class, new KmSignKRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityKmSignL.class, new KmSignLRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftAddedLane.class, new LeftAddedLaneRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy11.class, new Hwy11Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy12.class, new Hwy12Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy13.class, new Hwy13Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityParkingMeter.class, new ParkingMeterRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficLightLeftArrow.class, new TrafficLightLeftArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficLightRightArrow.class, new TrafficLightRightArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficLightStraightArrow.class, new TrafficLightStraightArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficLightStickLeftArrow.class, new StoplightStickLeftArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficLightStickRightArrow.class, new StoplightStickRightArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTrafficLightStickStraightArrow.class, new StoplightStickStraightArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy15.class, new Hwy15Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy9A.class, new Hwy9ARender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRightTurn.class, new RightTurnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLeftTurn.class, new LeftTurnRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFancyStreetlight.class, new FancyStreetlightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHalogenLight.class, new HalogenLightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRailwayCrossingLight.class, new RailwayCrossingLightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignA.class, new VariableSpeedSignARender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignB.class, new VariableSpeedSignBRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignC.class, new VariableSpeedSignCRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignD.class, new VariableSpeedSignDRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignE.class, new VariableSpeedSignERender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignF.class, new VariableSpeedSignFRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignG.class, new VariableSpeedSignGRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignH.class, new VariableSpeedSignHRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignI.class, new VariableSpeedSignIRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityVariableSpeedSignJ.class, new VariableSpeedSignJRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy14.class, new Hwy14Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy16.class, new Hwy16Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy17.class, new Hwy17Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy18.class, new Hwy18Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy19.class, new Hwy19Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy22.class, new Hwy22Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy23.class, new Hwy23Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy24.class, new Hwy24Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy25.class, new Hwy25Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy26.class, new Hwy26Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy27.class, new Hwy27Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy28.class, new Hwy28Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy29.class, new Hwy29Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy30.class, new Hwy30Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy31.class, new Hwy31Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy32.class, new Hwy32Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy33.class, new Hwy33Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy34.class, new Hwy34Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy35.class, new Hwy35Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy36.class, new Hwy36Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy38.class, new Hwy38Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy39.class, new Hwy39Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityHwy40.class, new Hwy40Render());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTallTrafficLight.class, new TallTrafficLightRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityTallTrafficLightYellow.class, new TallTrafficLightYellowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBarrier.class, new BarrierRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBarrierCorner.class, new BarrierCornerRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYellowLeftArrow.class, new YellowLeftArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYellowRightArrow.class, new YellowRightArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityYellowStraightArrow.class, new YellowStraightArrowRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityBusinessRoute.class, new BusinessRteRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGas.class, new GasSignRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityFourWay.class, new FourWayRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityThreeWay.class, new ThreeWayRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityRightTurnRed.class, new RightTurnRedRender());
      ClientRegistry.bindTileEntitySpecialRenderer(TileEntityCrosswalkLight.class, new CrosswalkLightRender());
   }

   public void capes() {
      DevCapes.getInstance().registerConfig("https://raw.githubusercontent.com/goldensilver853/files/master/capes.json", "monoblocks");
   }
}
